CREATE TABLE source.customers (
    customer_id BIGINT PRIMARY KEY,
    age INTEGER,
    gender VARCHAR,
    location VARCHAR,
    income_bracket VARCHAR,
    occupation VARCHAR,
    education_level VARCHAR,
    marital_status VARCHAR,
    household_size INTEGER,
    acquisition_channel VARCHAR,
    customer_segment VARCHAR,
    savings_account BOOLEAN,
    credit_card BOOLEAN,
    personal_loan BOOLEAN,
    investment_account BOOLEAN,
    insurance_product BOOLEAN,
    active_products INTEGER,
    app_logins_frequency INTEGER,
    feature_usage_diversity INTEGER,
    bill_payment_user BOOLEAN,
    auto_savings_enabled BOOLEAN,
    credit_utilization_ratio DOUBLE,
    international_transactions INTEGER,
    failed_transactions INTEGER,
    tx_count INTEGER,
    avg_tx_value DOUBLE,
    total_tx_volume DECIMAL(20,2),
    first_tx DATE,
    last_tx DATE,
    base_satisfaction DOUBLE,
    tx_satisfaction DOUBLE,
    product_satisfaction DOUBLE,
    satisfaction_score INTEGER,
    nps_score INTEGER,
    last_survey_date DATE,
    support_tickets_count INTEGER,
    resolved_tickets_ratio DOUBLE,
    app_store_rating DOUBLE,
    feedback_sentiment VARCHAR,
    feature_requests VARCHAR,
    complaint_topics VARCHAR,
    clv_segment VARCHAR,
    monthly_transaction_count DOUBLE,
    average_transaction_value DOUBLE,
    total_transaction_volume DECIMAL(20,2),
    transaction_frequency DOUBLE,
    last_transaction_date DATE,
    preferred_transaction_type VARCHAR,
    first_transaction_date DATE,
    weekend_transaction_ratio DOUBLE,
    avg_daily_transactions DOUBLE,
    customer_tenure DOUBLE,
    churn_probability DOUBLE,
    customer_lifetime_value DOUBLE
);

CREATE TABLE source.transactions (
    transaction_row_id BIGINT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    transaction_date DATE NOT NULL,
    amount_cop DECIMAL(20,2) NOT NULL,
    transaction_type VARCHAR NOT NULL,
    is_duplicate_looking BOOLEAN NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES source.customers(customer_id)
);
